### ISSUE TITLE
Guidelines on Gameplay

### ISSUE THREAD

**Issue by Inorizushi** [MidflightDigital/XX--STARLiGHT--twopointzero#1]
This theme does have Guidelines implemented, just disabled as they are still a WIP.

They currently do not support Scroll Changes and are not affected by Mini.

Code managing Guidelines can be found in:
BGAnimations/ScreenGameplay underlay/default.lua
BGAnimations/ScreenGameplay underlay/GuidePlus.lua
Modules/GuideDisplay.lua

**Comment by tertu-m** [comment]
i can take a look at this again. being on 5.3 only probably makes this a bit easier

**Comment by Inorizushi** [comment]
Issue fixed via usage of SM/OF's beatbars implementation.
