### ISSUE TITLE
bpm number issue on song list

### ISSUE THREAD

**Issue by BlueSupernova22** [MidflightDigital/XX--STARLiGHT--twopointzero#11]
on the song list the bpm numbers are shuffling as if on extra stage. is there anyway to fix that? I am using project outfox 5.3 alpha 4.11.0. And I am using starlight v2.0.2. This issue does not appear on other themes such as curilang's ddr a20.

as you can see from the screenshot. the bpm number just shuffles random numbers 
![starlight](https://user-images.githubusercontent.com/57787046/147804502-fa7f5f0f-58d0-4de2-bd27-cc08a2f38f1b.png)

**Comment by tertu-m** [comment]
This was a bug in Outfox alpha 4.11 that was fixed in Outfox alpha 4.12.
