### ISSUE TITLE
Song initialization window appearing too early

### ISSUE THREAD

**Issue by EtienneGL** [MidflightDigital/XX--STARLiGHT--twopointzero#16]
I found a small issue with the XX STARLiGHT -twopointzero- v2.1.0 hotfix. The window for the song initialization appears 2 frames before it does its full animation.
https://drive.google.com/file/d/1AXr2Jsptuhs1w2AknTKHTDY4ek0lW0OX/view?usp=sharing

**Comment by Inorizushi** [comment]
Fixed as of https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/commit/874ae3c7a48bcb3278d947923e713543517e0262
