### ISSUE TITLE
Cannot disable "danger" overlay

### ISSUE THREAD

**Issue by marioman63** [MidflightDigital/XX--STARLiGHT--twopointzero#17]
The only options for the danger overlay are "step zone" and "show". "ShowDanger" is set to 0 in OutFox's preferences.ini, yet it still shows with the theme.

**Comment by Inorizushi** [comment]
The theme doesn't currently use the ShowDanger preference. I'll add support for it with the next update.

**Comment by sumbodyscloser** [comment]
Yes please! Thank you

**Comment by Inorizushi** [comment]
Code added to repository copy. New official update still TBD.
