### ISSUE TITLE
Incorrect score picture on song results screen

### ISSUE THREAD

**Issue by Devin2048** [MidflightDigital/XX--STARLiGHT--twopointzero#19]
**Describe the bug**
When I got a score of 990,080, a AA+ picture was presented on [Results] instead of AAA.
When switching to [Select Music], the picture changed to a AAA.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - StepMania/Outfox Version alpha.4.13.0
 - Theme Version v2.1.0HF

**Additional context**
Not sure if this is tied to the theme or Outfox. I figured it's the theme because of "Scripts/99 Scoring.lua". I have not modified score values.

**Comment by HeeroJay** [comment]
Having this issue as well:

OS: Windows 10
StepMania/Outfox Version alpha 20220619
Theme Version v2.1.0HF
