### ISSUE TITLE
Crash due to missing metric group

### ISSUE THREAD

**Issue by animusyosho** [MidflightDigital/XX--STARLiGHT--twopointzero#27]
**Describe the bug**
Crash in certain circumstances due to missing metric group.

**To Reproduce**
1. Open Map Controllers menu in options.
2. 
![image](https://user-images.githubusercontent.com/17726978/167502635-0f4ab136-dc92-44e7-8fa6-6beb5de94868.png)

3. ![image](https://user-images.githubusercontent.com/17726978/167502659-17f3d115-b277-4cdc-831c-81d06d1ef82c.png)
CTD
**Expected behavior**

**Screenshots**
<img width="765" alt="image" src="https://user-images.githubusercontent.com/17726978/167502769-e31c4aff-cc8f-4223-b168-b9cb18b75e82.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Outfox Version 0.4.14.1
 - Theme Version 2.1.0HF2

**Comment by Inorizushi** [comment]
Fixed as of https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/commit/8f2114fac648afddd78587699fb8daee6bc51c27
