### ISSUE TITLE
Discord link dead in Releases tab

### ISSUE THREAD

**Issue by jmynes** [MidflightDigital/XX--STARLiGHT--twopointzero#37]
The custom [Discord link](https://discord.com/invite/xxstarlight) in the [Releases tab](https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/releases/tag/v2.1.0HF) has expired or is invalid.

Is there a new link, or is the server gone?

**Comment by Inorizushi** [comment]
Sorry about that, the discord server was unfortunately compromised due to one of the admins having their account hijacked for a couple days. The link was disabled to prevent people from joining in the meantime. The link is working again.

**Comment by brenkel** [comment]
i tried using the link but it still seems broken, is the discord server permanently shut off?
