### ISSUE TITLE
Avoid stretching images.

### ISSUE THREAD

**Issue by TheT113** [MidflightDigital/XX--STARLiGHT--twopointzero#38]
There are a lot of places where images are stretched, distorting their aspect ratio, when instead centering them and padding them with empty space would be a lot more preferable.

For example, in Wheel Type: Jukebox, groups without Jackets will stretch the Banner image to a square.

On Wheel Type: Wheel, Banners will be stretched to fit the 256x80 standard ratio, even if the banners aren't originally that size.

**Comment by Inorizushi** [comment]
Thanks for catching these, I thought I covered all of the resizing code for the group/song graphics but looks like I missed a couple. I'll have it fixed in a couple hours.

**Comment by TheT113** [comment]
I did notice another weird one; when you select a song with a non-standard Jacket size, it does display the Jacket correctly, but then briefly stretches it before the song starts.

**Comment by Inorizushi** [comment]
Fixed as of https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/commit/008e3173543a14812b13e6c64dbaf73086109c32
