### ISSUE TITLE
Custom judgment skins

### ISSUE THREAD

**Issue by MattMayuga** [MidflightDigital/XX--STARLiGHT--twopointzero#39]
Remember holidia and their unreleased DDR 1stReMIX theme? I think it's a cool feature to have on a DDR-styled SM5 theme. Of course, I do know themes like Simply Love have a very similar feature, but I'd like that to be implemented into the XX STARLiGHT theme so anyone can add their own judgment fonts, combo numbers, and the like.

# Overview
## How it works
The judgment skins can be changed in the player options menu. Here is a rundown of how each option works:
* Judgment changes the judgment font (Marvelous/Perfect/Great/Good/Miss). They are stored in the "judgments" folder and have the file name <Name of judgment font> 1x5.png
* Combo Font changes the combo font and label. The folder for it is "comboNumbers"
* Indicator changes the Fast/Slow and O.K./N.G. indicators. They are stored in the same judgment folder and to make them show up:
  * The name for the Fast/Slow indicator should be <Name of judgment font> [indicator] 1x5.png
  * The name for the O.K./N.G. indicator should be <Name of judgment font> [OKNG] 1x5.png
* FC Splash changes the GoodFC/GreatFC/PFC/MFC font when you clear songs with a full combo. These are stored in this directory: `fcSplash folder/<Name of judgment font>`.

**Comment by Inorizushi** [comment]
We've already talked about this amongst the team and we've decided that while it would be nice to have, we have no plans to implement this.
