### ISSUE TITLE
Selecting arrows is really up close to the screen. Very glitchy. 

### ISSUE THREAD

**Issue by Vibzzz981** [MidflightDigital/XX--STARLiGHT--twopointzero#40]

**Comment by Vibzzz981** [comment]
![Screenshot (96)](https://user-images.githubusercontent.com/111322488/218353103-54bbfd25-7587-4309-a89d-7f2e9d823a26.png)

**Comment by Inorizushi** [comment]
No information given on StepMania/OutFox version.
