### ISSUE TITLE
Repost - THE END OF DANCE DANCE REVOLUTION XX STARLIGHT

### ISSUE THREAD

**Issue by JmFantilaga** [MidflightDigital/XX--STARLiGHT--twopointzero#42]
HOLY FUCK
WHY TO BANNED MARSHMELLO_2091X ON HIS zenius-i-vanisher ACCOUNT
EVERYONE ITS TIME TO OFFICIALLY MASS DELETED AND SOME SIMFILES GETTING REMOVED PERMANENTLY PROJECT
Who needs
SIMFILES
Themes
Forums
Everyone i you want.
THIS IS LAST CHANCE TO GET AUTO REMOVE THIS PROJECT
THE FUCK IS COMING TO REMOVE THIS PROJECT
XX MODERATORS WILL DIE!!! oh it's RGTM and forcednautre WILL FUCKING DIE FOREVER!!

HOW TO DO LET'S GO BACK TO DDR SUPERNOVA 3 ON STEPMANIA

GOOD LUCK FUCKERS OF DANCE DANCE REVOLUTION XX STARLIGHT!!

![FUCKING GODZILLA](https://user-images.githubusercontent.com/104899325/224351403-e77895cd-b30d-47ee-8b79-82d6c7500382.png)

**Comment by JmFantilaga** [comment]
silverdragon754

Inorizushi

xRGTMx/Drisello

black4ever

KowalskiPenguin10897

DDRDAIKENKAI

riskofsoundingnerdy/leeium

Nicolas/Capacity

HypnoticMarten77
WILL DIE IF YOU POSTING A FUCK PICS
![download](https://user-images.githubusercontent.com/104899325/224352626-1534604c-dc50-4863-9641-55cee7a5c821.jpeg)

**Comment by JmFantilaga** [comment]
![bmiidx___noisy_doll_iroha_by_naokoko_d29qk9m-fullview](https://user-images.githubusercontent.com/104899325/224352822-f0336fd6-2d94-49d4-b99b-08e6240a5c8a.jpg)
TRY THIS 9TH STYLE THEME WHEN THE PROJECT IS GONE

**Comment by Inorizushi** [comment]
k
