### ISSUE TITLE
Fuck

### ISSUE THREAD

**Issue by nexustream** [MidflightDigital/XX--STARLiGHT--twopointzero#46]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - StepMania/Outfox Version
 - Theme Version [e.g. 2.1.0]

**Additional context**

**Comment by Inorizushi** [comment]
Thanks for the bug report
