### ISSUE TITLE
Danger is centered when Center1Player is enabled

### ISSUE THREAD

**Issue by JoseVarelaP** [MidflightDigital/XX--STARLiGHT--twopointzero#5]
Regardless if more than a single player has joined, if Center1Player is enabled, it will center the danger area to the player.

https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/blob/c81a3244bcbf1db3708de4b82d39e0b5c8894ef0/BGAnimations/ScreenGameplay%20underlay/default.lua#L72-L77

<img width="1080" alt="Captura de Pantalla" src="https://user-images.githubusercontent.com/23246027/143726109-f988f029-b9fc-4963-8c37-955fe9b9b8aa.png">

**Comment by Inorizushi** [comment]
This has been fixed https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/commit/345d246b6136924a0f5137038117221b6acc9083

https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/blob/071b824b92000e40da279c44782f88a4780e3d22/BGAnimations/ScreenGameplay%20underlay/default.lua#L73-L77

Will close when the hotfix is released
