### ISSUE TITLE
Wheel Type: Wheel does not work.

### ISSUE THREAD

**Issue by TheT113** [MidflightDigital/XX--STARLiGHT--twopointzero#68]
In the latest OutFox alpha test build, using the latest "cutting edge release" of the theme, multiple errors regarding missing files occur when attempting to use Wheel Type: Wheel.

**To Reproduce**
1. Download the latest OutFox alpha test build, "OutFox-alpha-0.5.0-pre043-a21c-Win64-date-20241005.exe"
2. Install the latest cutting edge release (installed 10/29/24).
3. Use OutFox options to change to theme.
4. Customize, Wheel Type, Wheel.
5. Game Mode, enter dancer name, Single.
6. Errors display.

**Expected behavior**
For Wheel to work.

**Screenshots**
![image](https://github.com/user-attachments/assets/c9900129-04a6-4cfb-b010-7482b75a6ddd)
![image](https://github.com/user-attachments/assets/4c65d8b7-d6fa-4d40-ae35-9b1f5d3e7570)
![image](https://github.com/user-attachments/assets/c68ebbfe-9fd7-4185-a873-fa75601101d0)
![image](https://github.com/user-attachments/assets/7ae27ab8-7261-4283-9d55-52b42d25ddf5)
![image](https://github.com/user-attachments/assets/3f64b0df-1572-43a0-afe6-5654ea5e5e4c)
![image](https://github.com/user-attachments/assets/4a63f13e-e616-42ce-95cb-d3f965b4a1b1)
![image](https://github.com/user-attachments/assets/7cab7819-b92f-4c73-a67a-cec7179ecb73)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 19045.5011
 - StepMania/Outfox Version: OutFox-alpha-0.5.0-pre043-a21c-Win64-date-20241005.exe
 - Theme Version: latest cutting edge release (installed 10/29/24)

**Comment by TheT113** [comment]
I decided to try it out with Beta 2, That does not display the errors, and the wheel "works", but it does not display a Jacket or Banner for any song. (I have confirmed the Jackets and Banners display in other themes.)

**Comment by Inorizushi** [comment]
Woops, I completely managed to mess up the pathing for a bunch of the wheels. I'll get them fixed up ASAP.

**Comment by Inorizushi** [comment]
Alright, all fixed up. Thanks for bringing it to our attention.

**Comment by TheT113** [comment]
Thank you so much for the quick fix! Looking good!
