### ISSUE TITLE
Full combo effect misaligned when center player 1 is enabled

### ISSUE THREAD

**Issue by SchneiderAFX** [MidflightDigital/XX--STARLiGHT--twopointzero#9]
![vlc_4rys6q1Pxl](https://user-images.githubusercontent.com/95201358/143807661-11ee1b3c-96da-4156-83fd-ca1337d8e261.jpg)

**Comment by SchneiderAFX** [comment]
may i add, it happens with the "game over" graphic too

**Comment by Inorizushi** [comment]
Fixed as of commit https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/commit/7a3cd955163afa101b203c88a49dc5f3f851748d

Please replace the two files that were edited.
